name: Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x test/gradlew

    - name: Build with Gradle
      working-directory: test
      run: ./gradlew build

    - name: Publish to GitHub Packages
      working-directory: test
      run: ./gradlew publish
      env:
        USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
